export const globalConstant = {
  SET_GLOBAL_VERSION: 'SET_GLOBAL_VERSION',
  SET_GLOBAL_IS_LOADING: 'SET_GLOBAL_IS_LOADING',
  SET_GLOBAL_IS_PREVIEWING: 'SET_GLOBAL_IS_PREVIEWING',
  SET_GLOBAL_FCM_REGID: 'SET_GLOBAL_FCM_REGID',
  SET_GLOBAL_REFERRER_ID: 'SET_GLOBAL_REFERRER_ID',
  SET_GLOBAL_TMP: 'SET_GLOBAL_TMP',
  SET_GLOBAL_ON_BOARDING: 'SET_GLOBAL_ON_BOARDING',
  SET_DEEP_LINK_NAV: 'SET_DEEP_LINK_NAV',
  SET_FORCE_CHANGE_PASSWORD: 'SET_FORCE_CHANGE_PASSWORD',
}
