export const productConstant = {
  ADMINISTRASI: 'ADMINISTRASI',
  BILLPAYMENT: 'BILLPAYMENT',
  ECOMMERCE: 'ECOMMERCE',
  EMONEY: 'EMONEY',
  TOPUPEMONEY: 'TOPUPEMONEY',
  GAME: 'GAME',
  PULSA: 'PULSA',
  TICKETING: 'TICKETING',
  WALLET: 'WALLET',
}
