export const storeConstant = {
  ID_TOKO: 'STORE_ID',
  NAMA_TOKO: 'STORE_NAME',
  DESKRIPSI: 'STORE_DESKRIPSI',
  TAGLINE: 'STORE_TAGLINE',
  ALAMAT: 'STORE_ALAMAT',
  KOTA: 'STORE_KOTA',
  PROPINSI: 'STORE_PROPINSI',
  LOCATION: 'STORE_LOCATION',
  CART_COUNT: 'CART_COUNT',
  ORDER_COUNT: 'ORDER_COUNT',
  PRODUCT_CATEGORY: 'PRODUCT_CATEGORY',
}
